<a href="https://colab.research.google.com/github/Sedzay/les4/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

#ЗАВДАННЯ 1

#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
mat_zero = np.zeros((3,3))
print(mat_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
mat_rand = np.random.randint(1,10,(5,5))
print(mat_rand)

[[2 1 9 5 1]
 [7 3 5 2 6]
 [4 5 5 4 8]
 [2 2 8 8 1]
 [3 4 3 6 9]]


In [4]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
mat_rand_2 = np.random.random((4,4))
print(mat_rand_2)

[[0.38641911 0.44046495 0.40475733 0.44225404]
 [0.03012328 0.77600531 0.55095838 0.3810734 ]
 [0.52926578 0.9568769  0.17582131 0.11830284]
 [0.86294567 0.07486688 0.82509486 0.83613181]]


In [5]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
mat_1 = np.random.randint(1,10,5)
mat_2 = np.random.randint(1,10,5)
sum = mat_1 + mat_2
minus = mat_1 - mat_2
mult = mat_1 * mat_2
print(mat_1)
print(mat_2)
print(sum)
print(minus)
print(mult)

[4 7 4 5 8]
[7 4 1 5 5]
[11 11  5 10 13]
[-3  3  3  0  3]
[28 28  4 25 40]


In [6]:
#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток
vec_1 = np.random.rand(7)
vec_2 = np.random.rand(7)
sk_mult = np.dot(vec_1,vec_2)
print("vec_1: ",vec_1)
print("vec_2: ",vec_2)
print("sk_mult: ",sk_mult)

vec_1:  [0.23769421 0.04486228 0.50543143 0.37625245 0.5928054  0.62994188
 0.14260031]
vec_2:  [0.9338413  0.94637988 0.60229666 0.38776628 0.363188   0.20434528
 0.27676506]
sk_mult:  1.0982353478002187


In [8]:
#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою
m_2_2 = np.random.randint(1,10,(2,2))
m_2_3 = np.random.randint(1,10,(2,3))
dot_mult = np.dot(m_2_2,m_2_3)
print("m_2_2: ",m_2_2)
print("m_2_3: ",m_2_3)
print("dot_mult: ",dot_mult)

m_2_2:  [[8 4]
 [3 4]]
m_2_3:  [[9 8 2]
 [6 4 1]]
dot_mult:  [[96 80 20]
 [51 40 10]]


In [9]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю
m_3_3 = np.random.randint(1,10,(2,2))
print("m_3_3: ",m_3_3)
m_inv = np.linalg.inv(m_3_3)
print("m_inv: ",m_inv)

m_3_3:  [[7 3]
 [4 5]]
m_inv:  [[ 0.2173913  -0.13043478]
 [-0.17391304  0.30434783]]


In [10]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її
m_4_4 = np.random.random((4,4))
print("m_4_4: ",m_4_4)
mT = m_4_4.T
print("mT: ",mT)

m_4_4:  [[0.1107879  0.3126403  0.45697913 0.65894007]
 [0.25425752 0.64110126 0.20012361 0.65762481]
 [0.77828922 0.7795984  0.61032815 0.30900035]
 [0.69773491 0.8596183  0.62532376 0.98240783]]
mT:  [[0.1107879  0.25425752 0.77828922 0.69773491]
 [0.3126403  0.64110126 0.7795984  0.8596183 ]
 [0.45697913 0.20012361 0.61032815 0.62532376]
 [0.65894007 0.65762481 0.30900035 0.98240783]]


In [11]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні
#від 1 до 10 та перемножте матрицю на вектор
m_3_4 = np.random.randint(1,10,(3,4))
vec_4 = np.random.randint(1,10,4)
print("m_3_4: ",m_3_4)
print("vec_4: ",vec_4)
mult_vex_mat = np.dot(m_3_4,vec_4)
print("mult_vex_mat: ",mult_vex_mat)

m_3_4:  [[2 4 2 5]
 [9 9 3 3]
 [8 3 2 3]]
vec_4:  [8 2 1 6]
mult_vex_mat:  [ 56 111  90]


In [12]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами
#в діапазоні від 0 до 1 та перемножте матрицю на вектор.
mat_2_3 = np.random.randint(1,10,(2,3))
vec_3 = np.random.randint(1,10,3)
print("mat_2_3: ",mat_2_3)
print("vec_3: ",vec_3)
mult_vex_mat = np.dot(mat_2_3,vec_3)
print("mult_vex_mat: ",mult_vex_mat)

mat_2_3:  [[4 6 3]
 [7 2 2]]
vec_3:  [6 3 6]
mult_vex_mat:  [60 60]


In [13]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
m1_2_2 = np.random.randint(1,10,(2,2))
m2_2_2 = np.random.randint(1,10,(2,2))
print("m1_2_2: ",m1_2_2)
print("m2_2_2: ",m2_2_2)
res = m1_2_2*m2_2_2
print("res: ",res)

m1_2_2:  [[7 5]
 [7 8]]
m2_2_2:  [[8 4]
 [1 3]]
res:  [[56 20]
 [ 7 24]]


In [14]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
m1_2_2 = np.random.randint(1,10,(2,2))
m2_2_2 = np.random.randint(1,10,(2,2))
print("m1_2_2: ",m1_2_2)
print("m2_2_2: ",m2_2_2)
res = np.dot(m1_2_2,m2_2_2)
print("res: ",res)

m1_2_2:  [[6 2]
 [2 1]]
m2_2_2:  [[4 7]
 [8 4]]
res:  [[40 50]
 [16 18]]


In [15]:
#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці
m100 = np.random.randint(1,100,(5,5))
print("m100: ",m100)
sum_el = np.sum(m100)
print("sum_el: ",sum_el)

m100:  [[43 62 38 81  3]
 [63 82 17 71 54]
 [99 97 48 49 10]
 [50 54 35  4 12]
 [50 30 37 94 68]]
sum_el:  1251


In [16]:
#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю
m1_4_4 = np.random.randint(1,10,(4,4))
m2_4_4 = np.random.randint(1,10,(4,4))
print("m1_4_4: ",m1_4_4)
print("m2_4_4: ",m2_4_4)
subtraction = m1_4_4 - m2_4_4
print("subtraction: ",subtraction)

m1_4_4:  [[2 5 5 6]
 [7 4 5 4]
 [8 8 3 5]
 [1 3 1 7]]
m2_4_4:  [[9 2 6 7]
 [5 7 6 1]
 [9 9 6 4]
 [3 9 8 2]]
subtraction:  [[-7  3 -1 -1]
 [ 2 -3 -1  3]
 [-1 -1 -3  1]
 [-2 -6 -7  5]]


In [17]:
#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
#в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
m_3_3 = np.random.rand(3,3)
print("m_3_3: ",m_3_3)
sum = np.sum(m_3_3, axis = 1,keepdims=True)
print("sum: ",sum)

m_3_3:  [[0.85689553 0.47298399 0.66327705]
 [0.80572861 0.2529805  0.07957344]
 [0.73276061 0.96139748 0.95380473]]
sum:  [[1.99315657]
 [1.13828255]
 [2.64796282]]


In [18]:
#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
m_3_4 = np.random.randint(np.iinfo(np.int32).min,np.iinfo(np.int32).max,(3,4))
print("m_3_4: ",m_3_4)
res = np.square(m_3_4)
print("res: ",res)

m_3_4:  [[  -40806268  -730096601   567760599   205273674]
 [ 1000705999 -1297207844  1728335668 -1067081812]
 [-1450638451  1328794273  -404236657  1828838545]]
res:  [[   1665151508087824  533041046791753201  322352097776838801
    42137281237458276]
 [1001412496434588001 1682748190535128336 2987144181281006224
  1138663593501203344]
 [2104351915519679401 1765694219957598529  163407274862535649
  3344650423677717025]]


In [19]:
#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами
#в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел
m_4 = np.random.randint(0,50,4)
print("m_4: ",m_4)
res = np.sqrt(m_4)
print("res: ",res)

m_4:  [24 23 42  8]
res:  [4.89897949 4.79583152 6.4807407  2.82842712]


In [20]:
#ЗАВДАННЯ 2

#1.Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("arr before: ",arr)
arr[arr%2 != 0] = -1
print("arr after: ",arr)

arr before:  [0 1 2 3 4 5 6 7 8 9]
arr after:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
#2.Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr_1d = np.random.randint(1,10,10)
print("arr_1d: ",arr_1d)
arr_2d = arr_1d.reshape(2, -1)
print("arr_2d: ",arr_2d)

arr_1d:  [9 8 1 7 1 8 5 6 2 6]
arr_2d:  [[9 8 1 7 1]
 [8 5 6 2 6]]


In [22]:
#3.Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
m1 = np.random.randint(1,10,10)
m2 = np.random.randint(1,10,10)
print("m1: ",m1)
print("m2: ",m2)
m3 = np.vstack((m1,m2))
print("m3: ",m3)

m1:  [6 4 5 4 7 6 1 1 7 2]
m2:  [9 1 4 3 7 6 5 6 8 4]
m3:  [[6 4 5 4 7 6 1 1 7 2]
 [9 1 4 3 7 6 5 6 8 4]]


In [23]:
#4.Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy
#і наведений нижче масив введення Input:a = np.array([1,2,3])
#Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
f = np.array([1, 2, 3])
repeated = np.repeat(f, 3)
print("repeated : ",repeated)
tile = np.tile(f,3)
print("tile : ",tile)
conc = np.concatenate((repeated,tile))
print("conc : ",conc)

repeated :  [1 1 1 2 2 2 3 3 3]
tile :  [1 2 3 1 2 3 1 2 3]
conc :  [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [24]:
#5.Отримайте спільні елементи між a і b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
com_el = np.intersect1d(a, b)
print("com_el: ",com_el)

com_el:  [2 4]


In [25]:
#6.Отримайте позиції перших 5 максимальних значень у заданому масиві a
np.random.seed(100)
ran_m = np.random.uniform(1,50, 20)
print("ran_m: ",ran_m)
sort_m = np.argsort(ran_m)[-5:]
res_5 = ran_m[sort_m]
print("res_5: ",res_5)

ran_m:  [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
res_5:  [40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [27]:
#7. Вилучіть усі значення NaN із одновимірного масиву
nan_m=np.array([1,2,3,np.nan,5,6,7,np.nan])
nan_m_clean = nan_m[~np.isnan(nan_m)]
print("nan_m_clean: ",nan_m_clean)

nan_m_clean:  [1. 2. 3. 5. 6. 7.]


In [28]:
#8. Обчисліть евклідову відстань між двома масивами a і b.
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
evclid_dist = np.linalg.norm(a - b)
print("evclid_dist: ",evclid_dist)

evclid_dist:  6.708203932499369


In [29]:
#9. Знайдіть індекс 5-го повторення числа 1 у масиві x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices_with_1 = np.where(x == 1)[0]
fifth_index = indices_with_1[4]
print("fifth_index: ",fifth_index)

fifth_index:  8


In [55]:
#10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.
# Input np.random.seed(100) a = np.random.randint(0, 5, 10) [0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Input: ", a)

# Знаходжу індекси повторювань
_, indices = np.unique(a, return_index=True)
#print(_)
#print(indices)
# Позначаю всі елементи як True
repeated = np.full_like(a, True)
#перші входження змінюю на false
repeated[indices] = False
#print(repeated)
#0->false,1->true
repeated = np.where(repeated, True, False)
print(repeated)



Input:  [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
